package abonamente.gui;

import abonamente.comparator.ComparatorCNP;
import abonamente.comparator.ComparatorNume;
import abonamente.comparator.ComparatorPrenume;
import abonamente.Contact;
import abonamente.controller.ContactController;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.ArrayList;
import java.util.List;
import javax.swing.DefaultListModel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author ciprian.anghel
 */
public class AgendaFrame extends javax.swing.JFrame {

    List<Contact> contacte;
    DefaultTableModel dtm;

    public AgendaFrame() {
        initComponents();
        buttonGroup1.add(radioSortareDupaNume);
        buttonGroup1.add(radioSortareDupaPrenume);
        buttonGroup1.add(radioSortareDupaCNP);
        contacte = new ArrayList<>();
        dtm = new DefaultTableModel();
        dtm.setColumnIdentifiers(new String[]{"Nume", "Prenume", "CNP", "Numar de telefon"});
        tabelContacte.setModel(dtm);
        afisareContacte();
        addListeners();
    }

    private void afisareContacte() {
        if (dtm.getRowCount() > 0) {
            for (int i = dtm.getRowCount() - 1; i > -1; i--) {
                dtm.removeRow(i);
            }
        }

        for (Contact contact : contacte) {
            dtm.addRow(new String[]{
                contact.getAbonat().getNume(),
                contact.getAbonat().getPrenume(),
                contact.getAbonat().getCnp(),
                contact.getNrTel().getNr()
            });
        }
    }

    private void addListeners() {
        jCreateContact.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                adaugaContact();
            }
        });
        buttonSort.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                if (radioSortareDupaNume.isSelected()) {
                    ContactController.getInstance().sortare(contacte, new ComparatorNume());
                    afisareContacte();
                } else if (radioSortareDupaPrenume.isSelected()) {
                    ContactController.getInstance().sortare(contacte, new ComparatorPrenume());
                    afisareContacte();
                } else {
                    ContactController.getInstance().sortare(contacte, new ComparatorCNP());
                    afisareContacte();
                }
            }
        });
    }

    public void adaugaContact() {
        String nume = numeTextField.getText();
        String prenume = prenumeTextField.getText();
        String cnp = cnpTextField.getText();
        String numar = tfNumarTel.getText();
        Contact contact = ContactController.getInstance().createContact(nume, prenume, cnp, numar);
        contacte.add(contact);
        afisareContacte();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonSort = new javax.swing.JButton();
        radioSortareDupaNume = new javax.swing.JRadioButton();
        radioSortareDupaPrenume = new javax.swing.JRadioButton();
        radioSortareDupaCNP = new javax.swing.JRadioButton();
        numeTextField = new javax.swing.JTextField();
        prenumeTextField = new javax.swing.JTextField();
        cnpTextField = new javax.swing.JTextField();
        tfNumarTel = new javax.swing.JTextField();
        tfNume = new javax.swing.JLabel();
        tfPrenume = new javax.swing.JLabel();
        tfCNP = new javax.swing.JLabel();
        nrTelTextField = new javax.swing.JLabel();
        jCreateContact = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tabelContacte = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Proiect - Anghel Ciprian Liviu");
        setResizable(false);

        buttonSort.setText("Sort");
        buttonSort.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonSortActionPerformed(evt);
            }
        });

        radioSortareDupaNume.setText("Sortare dupa nume");

        radioSortareDupaPrenume.setText("Sortare dupa prenume");

        radioSortareDupaCNP.setText("Sortare dupa CNP");

        tfNume.setText("Nume");

        tfPrenume.setText("Prenume");

        tfCNP.setText("CNP");

        nrTelTextField.setText("Numar Telefon");

        jCreateContact.setText("Inserare Contact");
        jCreateContact.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCreateContactActionPerformed(evt);
            }
        });

        tabelContacte.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(tabelContacte);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(radioSortareDupaCNP)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(numeTextField)
                            .addComponent(buttonSort, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(prenumeTextField)
                            .addComponent(cnpTextField)
                            .addComponent(tfNumarTel)
                            .addComponent(jCreateContact, javax.swing.GroupLayout.DEFAULT_SIZE, 125, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(nrTelTextField)
                            .addComponent(tfCNP)
                            .addComponent(tfPrenume)
                            .addComponent(tfNume)))
                    .addComponent(radioSortareDupaPrenume)
                    .addComponent(radioSortareDupaNume))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 429, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(numeTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tfNume))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(prenumeTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tfPrenume))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cnpTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tfCNP))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tfNumarTel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(nrTelTextField))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jCreateContact)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(radioSortareDupaNume)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(radioSortareDupaPrenume)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(radioSortareDupaCNP)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(buttonSort)
                        .addGap(5, 5, 5))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buttonSortActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonSortActionPerformed
            //am creat metoda addListeners()
            //nu am stiut cum sa mai sterg aceasta metoda
    }//GEN-LAST:event_buttonSortActionPerformed

    private void jCreateContactActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCreateContactActionPerformed
            //am creat metoda addListeners()
            //nu am stiut cum sa mai sterg aceasta metoda
    }//GEN-LAST:event_jCreateContactActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AgendaFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AgendaFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AgendaFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AgendaFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AgendaFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton buttonSort;
    private javax.swing.JTextField cnpTextField;
    private javax.swing.JButton jCreateContact;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel nrTelTextField;
    private javax.swing.JTextField numeTextField;
    private javax.swing.JTextField prenumeTextField;
    private javax.swing.JRadioButton radioSortareDupaCNP;
    private javax.swing.JRadioButton radioSortareDupaNume;
    private javax.swing.JRadioButton radioSortareDupaPrenume;
    private javax.swing.JTable tabelContacte;
    private javax.swing.JLabel tfCNP;
    private javax.swing.JTextField tfNumarTel;
    private javax.swing.JLabel tfNume;
    private javax.swing.JLabel tfPrenume;
    // End of variables declaration//GEN-END:variables

}
